// DEV/TEMP/kbpp-react-test/client/components/Footer.tsx
import { Separator } from "@/components/ui/separator";
import { Github, Mail, Sparkles } from "lucide-react";
import { Link } from "react-router-dom";

const footerSections = [
  {
    title: "KBPP",
    links: [
      { name: "Features", href: "/features" },
      { name: "Pricing", href: "/pricing" },
      { name: "Documentation", href: "/docs" },
      { name: "API Reference", href: "/api" },
    ],
  },
  {
    title: "Company",
    links: [
      { name: "About", href: "/about" },
      { name: "Blog", href: "/blog" },
      { name: "Careers", href: "/careers" },
      { name: "Contact", href: "/contact" },
    ],
  },
  {
    title: "Legal",
    links: [
      { name: "Privacy Policy", href: "/privacy" },
      { name: "Terms of Service", href: "/terms" },
      { name: "Cookie Policy", href: "/cookies" },
      { name: "Security", href: "/security" },
    ],
  },
];

const socialLinks = [
  { name: "GitHub", icon: Github, href: "https://github.com" },
  { name: "Email", icon: Mail, href: "mailto:business@kbpartpicker.app" },
];

export function Footer() {
  return (
    <footer className="border-t" style={{ backgroundColor: "hsl(220 8% 9%)" }}>
      <div className="container py-16">
        <div className="grid grid-cols-2 md:grid-cols-6 gap-8">
          {/* Logo and Description */}
          <div className="col-span-2">
            <Link to="/" className="flex items-center space-x-2 mb-4">
              <div
                className="flex h-8 w-8 items-center justify-center rounded-md"
                style={{ background: "var(--linearPrimarySecondary)" }}
              >
                <Sparkles className="h-5 w-5 text-white" />
              </div>
              <span
                className="font-bold text-xl bg-clip-text text-transparent"
                style={{
                  background: "var(--linearPrimarySecondary)",
                  backgroundClip: "text",
                }}
              >
                KBPartPicker
              </span>
            </Link>
            <p className="text-muted-foreground text-sm mb-6 max-w-xs">
              Build keyboards with our cutting-edge platform.
              Designed to bring your dream build to life
              with precision
            </p>
            <div className="flex space-x-4">
              {socialLinks.map((social) => (
                <a
                  key={social.name}
                  href={social.href}
                  className="text-muted-foreground hover:text-foreground transition-colors"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <social.icon className="h-5 w-5" />
                  <span className="sr-only">{social.name}</span>
                </a>
              ))}
            </div>
          </div>

          {/* Footer Sections */}
          {footerSections.map((section) => (
            <div key={section.title}>
              <h3 className="font-semibold text-foreground mb-4">
                {section.title}
              </h3>
              <ul className="space-y-3">
                {section.links.map((link) => (
                  <li key={link.name}>
                    <Link
                      to={link.href}
                      className="text-sm text-muted-foreground hover:text-foreground transition-colors"
                    >
                      {link.name}
                    </Link>
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>

        <Separator className="my-8" />

        <div className="flex flex-col md:flex-row justify-between items-center">
          <p className="text-sm text-muted-foreground">
            © 2025 KBPartPicker. All rights reserved.
          </p>
          <div className="flex items-center space-x-6 mt-4 md:mt-0">
            <Link
              to="/privacy"
              className="text-sm text-muted-foreground hover:text-foreground transition-colors"
            >
              Privacy
            </Link>
            <Link
              to="/terms"
              className="text-sm text-muted-foreground hover:text-foreground transition-colors"
            >
              Terms
            </Link>
            <Link
              to="/cookies"
              className="text-sm text-muted-foreground hover:text-foreground transition-colors"
            >
              Cookies
            </Link>
          </div>
        </div>
      </div>
    </footer>
  );
}

// DEV/TEMP/kbpp-vue-0.3/src/components/Footer.vue
<template>
  <footer class="border-t" style="background-color: hsl(220 8% 9%)">
    <div class="container py-16">
      <div class="grid grid-cols-2 md:grid-cols-6 gap-8">
        <!-- Logo and Description -->
        <div class="col-span-2">
          <router-link to="/" class="flex items-center space-x-2 mb-4">
            <div
              class="flex h-8 w-8 items-center justify-center rounded-md"
              style="background: var(--linearPrimarySecondary)"
            >
              <SparklesIcon class="h-5 w-5 text-white" />
            </div>
            <span
              class="font-bold text-xl bg-clip-text text-transparent"
              style="background: var(--linearPrimarySecondary); background-clip: text"
            >
              KBPartPicker
            </span>
          </router-link>
          <p class="text-muted-foreground text-sm mb-6 max-w-xs">
            Build keyboards with our cutting-edge platform. Designed to bring
            your dream build to life with precision.
          </p>
          <div class="flex space-x-4">
            <a
              v-for="social in socialLinks"
              :key="social.name"
              :href="social.href"
              target="_blank"
              rel="noopener noreferrer"
              class="text-muted-foreground hover:text-foreground transition-colors"
            >
              <social.icon class="h-5 w-5" />
              <span class="sr-only">{{ social.name }}</span>
            </a>
          </div>
        </div>

        <!-- Footer Sections -->
        <div v-for="section in footerSections" :key="section.title">
          <h3 class="font-semibold text-foreground mb-4">{{ section.title }}</h3>
          <ul class="space-y-3">
            <li v-for="link in section.links" :key="link.name">
              <router-link
                :to="link.href"
                class="text-sm text-muted-foreground hover:text-foreground transition-colors"
              >
                {{ link.name }}
              </router-link>
            </li>
          </ul>
        </div>
      </div>

      <hr class="my-8" />

      <div class="flex flex-col md:flex-row justify-between items-center">
        <p class="text-sm text-muted-foreground">
          © 2025 KBPartPicker. All rights reserved.
        </p>
        <div class="flex items-center space-x-6 mt-4 md:mt-0">
          <router-link to="/privacy" class="text-sm text-muted-foreground hover:text-foreground">
            Privacy
          </router-link>
          <router-link to="/terms" class="text-sm text-muted-foreground hover:text-foreground">
            Terms
          </router-link>
          <router-link to="/cookies" class="text-sm text-muted-foreground hover:text-foreground">
            Cookies
          </router-link>
        </div>
      </div>
    </div>
  </footer>
</template>

<script setup lang="ts">
import { SparklesIcon } from '@heroicons/vue/24/outline'; // Replace with your icon library

const footerSections = [
  {
    title: 'KBPP',
    links: [
      { name: 'Features', href: '/features' },
      { name: 'Pricing', href: '/pricing' },
      { name: 'Documentation', href: '/docs' },
      { name: 'API Reference', href: '/api' },
    ],
  },
  {
    title: 'Company',
    links: [
      { name: 'About', href: '/about' },
      { name: 'Blog', href: '/blog' },
      { name: 'Careers', href: '/careers' },
      { name: 'Contact', href: '/contact' },
    ],
  },
  {
    title: 'Legal',
    links: [
      { name: 'Privacy Policy', href: '/privacy' },
      { name: 'Terms of Service', href: '/terms' },
      { name: 'Cookie Policy', href: '/cookies' },
      { name: 'Security', href: '/security' },
    ],
  },
];

const socialLinks = [
  { name: 'GitHub', icon: SparklesIcon, href: 'https://github.com' },
  { name: 'Email', icon: SparklesIcon, href: 'mailto:business@kbpartpicker.app' },
];
</script>

<style scoped>
/* Add any additional styles here */
</style>
